// Code generated by Wire. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package server

import (
	"github.com/danielmesquitta/flight-api/internal/app/server/handler"
	"github.com/danielmesquitta/flight-api/internal/app/server/middleware"
	"github.com/danielmesquitta/flight-api/internal/app/server/router"
	"github.com/danielmesquitta/flight-api/internal/config/env"
	"github.com/danielmesquitta/flight-api/internal/pkg/jwtutil"
	"github.com/danielmesquitta/flight-api/internal/pkg/validator"
	"github.com/danielmesquitta/flight-api/internal/provider/cache"
	"github.com/danielmesquitta/flight-api/internal/provider/cache/rediscache"
	"github.com/google/wire"
	"testing"
)

// NewProd wires up the application in prod mode.
func NewProd(
	v validator.Validator,
	e *env.Env,
	t *testing.T,
) *App {
	wire.Build(
		// Specific prod providers
		jwtutil.NewJWT,
		wire.Bind(new(cache.Cache), new(*rediscache.RedisCache)),
		rediscache.NewRedisCache,
		handler.NewDocHandler,
		handler.NewHealthHandler,
		middleware.NewMiddleware,
		router.NewRouter,
		Build,
	)
	return &App{}
}

// NewDev wires up the application in dev mode.
func NewDev(
	v validator.Validator,
	e *env.Env,
	t *testing.T,
) *App {
	wire.Build(
		// Specific dev providers
		jwtutil.NewJWT,
		wire.Bind(new(cache.Cache), new(*rediscache.RedisCache)),
		rediscache.NewRedisCache,
		handler.NewDocHandler,
		handler.NewHealthHandler,
		middleware.NewMiddleware,
		router.NewRouter,
		Build,
	)
	return &App{}
}

// NewStaging wires up the application in staging mode.
func NewStaging(
	v validator.Validator,
	e *env.Env,
	t *testing.T,
) *App {
	wire.Build(
		// Specific staging providers
		jwtutil.NewJWT,
		wire.Bind(new(cache.Cache), new(*rediscache.RedisCache)),
		rediscache.NewRedisCache,
		handler.NewDocHandler,
		handler.NewHealthHandler,
		middleware.NewMiddleware,
		router.NewRouter,
		Build,
	)
	return &App{}
}

// NewTest wires up the application in test mode.
func NewTest(
	v validator.Validator,
	e *env.Env,
	t *testing.T,
) *App {
	wire.Build(
		// Specific test providers
		jwtutil.NewJWT,
		wire.Bind(new(cache.Cache), new(*rediscache.RedisCache)),
		rediscache.NewRedisCache,
		handler.NewDocHandler,
		handler.NewHealthHandler,
		middleware.NewMiddleware,
		router.NewRouter,
		Build,
	)
	return &App{}
}
