components:
    schemas:
        dto.ErrorItem:
            properties:
                name:
                    type: string
                reason:
                    type: string
            type: object
        dto.ErrorResponse:
            properties:
                errors:
                    items:
                        $ref: '#/components/schemas/dto.ErrorItem'
                    type: array
                message:
                    type: string
            type: object
        dto.HealthResponse:
            properties:
                status:
                    type: string
            type: object
    securitySchemes:
        BasicAuth:
            scheme: basic
            type: http
        BearerAuth:
            description: Type "Bearer" followed by a space and JWT token.
            in: header
            name: Authorization
            type: apiKey
info:
    contact:
        email: danielmesquitta123@gmail.com
        name: Daniel Mesquita
    description: Flight API
    title: Flight API
    version: "1.0"
openapi: 3.0.3
paths:
    /health:
        post:
            description: Health check
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/dto.HealthResponse'
                    description: OK
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/dto.ErrorResponse'
                    description: Internal Server Error
            summary: Health check
            tags:
                - Health
